ALTER TABLE podcast_syndications 
ADD COLUMN IF NOT EXISTS is_managed_by_platform BOOLEAN NOT NULL DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS is_claimed_by_creator BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS claim_token VARCHAR(100),
ADD COLUMN IF NOT EXISTS claimed_at TIMESTAMP WITH TIME ZONE;
